package una.progra4.huber.domain;
// Generated 30-sep-2017 15:36:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private ServicioId id;
     private Usuario usuarioByUsuarioTripulante;
     private Usuario usuarioByUsuarioConductor;
     private Veiculo veiculo;
     private int ubicacionInicio;
     private int ubicacionFin;
     private Date horaIn;
     private Date horaFn;
     private Long costo;
     private Integer puntuacion;
     private String retroalimentacion;
     private Date fecha;

    public Servicio() {
    }

	
    public Servicio(ServicioId id, Usuario usuarioByUsuarioTripulante, Usuario usuarioByUsuarioConductor, Veiculo veiculo, int ubicacionInicio, int ubicacionFin, Date fecha) {
        this.id = id;
        this.usuarioByUsuarioTripulante = usuarioByUsuarioTripulante;
        this.usuarioByUsuarioConductor = usuarioByUsuarioConductor;
        this.veiculo = veiculo;
        this.ubicacionInicio = ubicacionInicio;
        this.ubicacionFin = ubicacionFin;
        this.fecha = fecha;
    }
    public Servicio(ServicioId id, Usuario usuarioByUsuarioTripulante, Usuario usuarioByUsuarioConductor, Veiculo veiculo, int ubicacionInicio, int ubicacionFin, Date horaIn, Date horaFn, Long costo, Integer puntuacion, String retroalimentacion, Date fecha) {
       this.id = id;
       this.usuarioByUsuarioTripulante = usuarioByUsuarioTripulante;
       this.usuarioByUsuarioConductor = usuarioByUsuarioConductor;
       this.veiculo = veiculo;
       this.ubicacionInicio = ubicacionInicio;
       this.ubicacionFin = ubicacionFin;
       this.horaIn = horaIn;
       this.horaFn = horaFn;
       this.costo = costo;
       this.puntuacion = puntuacion;
       this.retroalimentacion = retroalimentacion;
       this.fecha = fecha;
    }
   
    public ServicioId getId() {
        return this.id;
    }
    
    public void setId(ServicioId id) {
        this.id = id;
    }
    public Usuario getUsuarioByUsuarioTripulante() {
        return this.usuarioByUsuarioTripulante;
    }
    
    public void setUsuarioByUsuarioTripulante(Usuario usuarioByUsuarioTripulante) {
        this.usuarioByUsuarioTripulante = usuarioByUsuarioTripulante;
    }
    public Usuario getUsuarioByUsuarioConductor() {
        return this.usuarioByUsuarioConductor;
    }
    
    public void setUsuarioByUsuarioConductor(Usuario usuarioByUsuarioConductor) {
        this.usuarioByUsuarioConductor = usuarioByUsuarioConductor;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public int getUbicacionInicio() {
        return this.ubicacionInicio;
    }
    
    public void setUbicacionInicio(int ubicacionInicio) {
        this.ubicacionInicio = ubicacionInicio;
    }
    public int getUbicacionFin() {
        return this.ubicacionFin;
    }
    
    public void setUbicacionFin(int ubicacionFin) {
        this.ubicacionFin = ubicacionFin;
    }
    public Date getHoraIn() {
        return this.horaIn;
    }
    
    public void setHoraIn(Date horaIn) {
        this.horaIn = horaIn;
    }
    public Date getHoraFn() {
        return this.horaFn;
    }
    
    public void setHoraFn(Date horaFn) {
        this.horaFn = horaFn;
    }
    public Long getCosto() {
        return this.costo;
    }
    
    public void setCosto(Long costo) {
        this.costo = costo;
    }
    public Integer getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(Integer puntuacion) {
        this.puntuacion = puntuacion;
    }
    public String getRetroalimentacion() {
        return this.retroalimentacion;
    }
    
    public void setRetroalimentacion(String retroalimentacion) {
        this.retroalimentacion = retroalimentacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


