package una.progra4.huber.domain;
// Generated 30-sep-2017 15:36:55 by Hibernate Tools 4.3.1



/**
 * ServicioId generated by hbm2java
 */
public class ServicioId  implements java.io.Serializable {


     private int id;
     private int veiculoPlaca;

    public ServicioId() {
    }

    public ServicioId(int id, int veiculoPlaca) {
       this.id = id;
       this.veiculoPlaca = veiculoPlaca;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getVeiculoPlaca() {
        return this.veiculoPlaca;
    }
    
    public void setVeiculoPlaca(int veiculoPlaca) {
        this.veiculoPlaca = veiculoPlaca;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServicioId) ) return false;
		 ServicioId castOther = ( ServicioId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getVeiculoPlaca()==castOther.getVeiculoPlaca());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getVeiculoPlaca();
         return result;
   }   


}


